#!/usr/bin/env node
/**
 * Check the Discovered or Invented bank.
 *
 * Every item needs both languages, a real answer, a "why" that teaches and a
 * source a grown-up can open to check it. The two answers should be close to
 * half and half: a bank that leans one way teaches a child to guess that way.
 *
 * The bank was asked for as six examples plus a hundred more. Those six must
 * stay, with the answers they were given, and the bank must not shrink below
 * 106. It may grow: a floor, not an exact count, so adding a good question
 * never means deleting one.
 *
 *   node tools/discovercheck.mjs           check
 *   node tools/discovercheck.mjs --write   check, then rewrite the credits page
 */

import fs from 'node:fs';

const FILE = 'data/fun/discover.json';
const CREDITS = 'docs/research/discover/CREDITS.md';
const MIN_ITEMS = 106;
/* The six the bank was built from, word for word as the family gave them. */
const REQUIRED = {
  water: 'discovered', wheel: 'invented', gold: 'discovered',
  electricity: 'discovered', fire: 'discovered', computers: 'invented'
};
const errors = [];
const warnings = [];
const err = (m) => errors.push(m);
const warn = (m) => warnings.push(m);

const data = JSON.parse(fs.readFileSync(FILE, 'utf8'));
const { ANSWERS } = await import('../assets/js/modules/discover.js');

for (const a of ANSWERS) {
  for (const lang of ['en', 'es']) {
    if (!data.rule?.[a]?.[lang]) err(`rule for "${a}" has no ${lang} text`);
  }
}

if (!Array.isArray(data.items)) {
  err('"items" must be a list');
  data.items = [];
}

const ids = new Set();
const questions = new Map();
const count = Object.fromEntries(ANSWERS.map((a) => [a, 0]));

for (const [i, x] of data.items.entries()) {
  const where = `item ${i + 1} (${x.id || '?'})`;
  if (!x.id || !/^[a-z0-9-]+$/.test(x.id)) err(`${where}: id must be lower-case words joined by -`);
  if (ids.has(x.id)) err(`${where}: duplicate id`);
  ids.add(x.id);
  if (!ANSWERS.includes(x.answer)) { err(`${where}: answer must be ${ANSWERS.join(' or ')}`); continue; }
  count[x.answer] += 1;
  if (!x.emoji) err(`${where}: no emoji`);
  if (!/^https:\/\/[^\s]+$/.test(x.source || '')) err(`${where}: no source link (https://...)`);

  for (const lang of ['en', 'es']) {
    const q = x.q?.[lang] || '';
    const why = x.why?.[lang] || '';
    if (!q) { err(`${where}: no ${lang} question`); continue; }
    if (!why) err(`${where}: no ${lang} why`);
    if (lang === 'en' && !/^(Was|Were) .+ discovered or invented\?$/.test(q)) {
      err(`${where}: English question should read "Was/Were ... discovered or invented?"`);
    }
    if (lang === 'es' && !/^¿.+ se (descubrió o se inventó|descubrieron o se inventaron)\?$/.test(q)) {
      err(`${where}: Spanish question should read "¿... se descubrió o se inventó?"`);
    }
    const key = `${lang}:${q.toLowerCase()}`;
    if (questions.has(key)) err(`${where}: same question as ${questions.get(key)}`);
    questions.set(key, x.id);
    if (why.length > 220) warn(`${where}: ${lang} why is ${why.length} chars; keep it short`);
    if (/\bwrong\b/i.test(why)) warn(`${where}: ${lang} why says "wrong"`);
  }
}

const total = ids.size;
if (total < MIN_ITEMS) err(`only ${total} items; the bank must keep at least ${MIN_ITEMS}`);
for (const [id, answer] of Object.entries(REQUIRED)) {
  const x = data.items.find((y) => y.id === id);
  if (!x) err(`the example "${id}" is missing`);
  else if (x.answer !== answer) err(`the example "${id}" must be ${answer}, not ${x.answer}`);
}

/* ---- the credits page: one line per question, with its link ---- */
const credits = `# Discovered or Invented? — sources

Generated by \`node tools/discovercheck.mjs --write\`. Do not edit by hand:
change \`source\` in \`data/fun/discover.json\` and run it again.

Each question links to the English Wikipedia page that backs its "why" line.
Last review: ${data.review?.checked || 'not recorded'}. ${data.review?.note || ''}

To correct a fact: fix the \`why\` text in both languages, fix or replace the
\`source\`, and run the command above.

| Question | Answer | Source |
|---|---|---|
${data.items.map((x) => `| ${x.q?.en || x.id} | ${x.answer} | <${x.source}> |`).join('\n')}
`;
if (process.argv.includes('--write')) {
  fs.mkdirSync('docs/research/discover', { recursive: true });
  fs.writeFileSync(CREDITS, credits);
  console.log(`wrote ${CREDITS}`);
} else if (!fs.existsSync(CREDITS) || fs.readFileSync(CREDITS, 'utf8') !== credits) {
  err(`${CREDITS} is out of date; run node tools/discovercheck.mjs --write`);
}
const [a, b] = ANSWERS.map((k) => count[k]);
if (total && Math.abs(a - b) / total > 0.1) {
  err(`answers lean one way: ${ANSWERS.map((k) => `${count[k]} ${k}`).join(', ')}`);
}

console.log(`${total} items: ${ANSWERS.map((k) => `${count[k]} ${k}`).join(', ')}`);
if (warnings.length) {
  console.log(`\nwarnings (${warnings.length}):`);
  warnings.forEach((m) => console.log(`  ! ${m}`));
}
if (errors.length) {
  console.log(`\nERRORS (${errors.length}):`);
  errors.forEach((m) => console.log(`  x ${m}`));
  process.exit(1);
}
console.log('\nNo errors.');
