#!/usr/bin/env node
/**
 * Check the Math Brain Teasers bank.
 *
 * Every teaser was found somewhere and retold, so the source is required. The
 * answers are not taken on trust: a numeric teaser carries `check`, the sum
 * that works it out from the numbers in the question, and this evaluates it
 * and holds the right choice to the result. Web lists of riddles have
 * mistakes in them; this is where one would be caught.
 *
 *   node tools/teaserscheck.mjs           check
 *   node tools/teaserscheck.mjs --write   check, then rewrite the manifest and
 *                                         the credits page from the bank
 */

import fs from 'node:fs';

const DIR = 'data/teasers';
const MANIFEST = `${DIR}/manifest.json`;
const CREDITS = 'docs/research/teasers/CREDITS.md';
const MIN = 100;
const MAX = 200;

const { LEVEL_IDS } = await import('../assets/js/modules/teasers.js');
const { ROOMS } = await import('../assets/js/modules/sections.js');
const { LEVELS, problems, fold } = await import('./teaserschema.mjs');

/* The seven the family asked for by name, with the answers they gave. */
const ASKED = [
  [/30 by ½|30 by 1\/2|30 by one half/i, /70/],
  [/butcher/i, /meat/i],
  [/19 sheep/i, /^7\b|seven/i],
  [/18 white socks/i, /^3\b|three/i],
  [/52 days/i, /51/],
  [/eight 8s|eight eights/i, /888/],
  [/Ashley/, /22/]
];

const errors = [];
const warnings = [];
const err = (m) => errors.push(m);
const warn = (m) => warnings.push(m);
const words = (s) => new Set(fold(s).split(' ').filter((w) => w.length > 2));

const bank = {};
const review = {};
const all = [];
for (const level of LEVEL_IDS) {
  const file = `${DIR}/${level}.json`;
  if (!fs.existsSync(file)) { err(`${file} is missing`); bank[level] = []; continue; }
  const data = JSON.parse(fs.readFileSync(file, 'utf8'));
  bank[level] = Array.isArray(data.items) ? data.items : [];
  if (!Array.isArray(data.items)) err(`${file}: "items" must be a list`);
  review[level] = data.esReview || null;
  all.push(...bank[level]);
}

const ids = new Set();
const seenQ = new Map();
for (const level of LEVEL_IDS) {
  for (const [i, x] of bank[level].entries()) {
    const where = `${level} ${i + 1} (${x.id || '?'})`;
    for (const p of problems(x, level)) err(`${where}: ${p}`);
    if (ids.has(x.id)) err(`${where}: duplicate id`);
    ids.add(x.id);
    for (const lang of ['en', 'es']) {
      if (/\bwrong\b/i.test(x.why?.[lang] || '')) warn(`${where}: ${lang} why says "wrong"`);
    }
    const key = fold(x.q?.en);
    if (seenQ.has(key)) err(`${where}: same question as ${seenQ.get(key)}`);
    seenQ.set(key, x.id);
  }
  const n = bank[level].length;
  if (n < MIN || n > MAX) err(`${level}: ${n} teasers; each level needs ${MIN} to ${MAX}`);

  /* The Spanish is read by a person before release. Recorded per level, as
     { "by", "date", "native": true }; until then this stays a warning, so
     the build is not blocked by work only a person can do. */
  const r = review[level];
  if (!r || !r.native || !r.by || !/^\d{4}-\d{2}-\d{2}$/.test(r.date || '')) {
    warn(`${level}: the Spanish has not had a native speaker's read-through (esReview in ${level}.json)`);
  }
}

/* The same puzzle with a few words changed. Close pairs are listed, not
   refused: two teasers can share most words and still ask different things. */
const bags = all.map((x) => ({ id: x.id, w: words(x.q?.en) }));
for (let i = 0; i < bags.length; i += 1) {
  for (let j = i + 1; j < bags.length; j += 1) {
    const a = bags[i].w;
    const b = bags[j].w;
    if (a.size < 6 || b.size < 6) continue;
    let both = 0;
    for (const w of a) if (b.has(w)) both += 1;
    const jac = both / (a.size + b.size - both);
    if (jac > 0.75) warn(`${bags[i].id} and ${bags[j].id} look like the same teaser (${Math.round(jac * 100)}% same words)`);
  }
}

for (const [q, a] of ASKED) {
  const x = all.find((y) => q.test(y.q?.en || ''));
  if (!x) err(`the family's example ${q} is missing`);
  else if (!a.test(x.choices?.[x.answer]?.en || '')) err(`${x.id}: the family's example has the answer "${x.choices?.[x.answer]?.en}"`);
}

/* ---- the manifest the setup card reads, and the room's count ---- */
const manifest = {
  levels: LEVEL_IDS.map((id) => ({ id, name: LEVELS[id].name, ages: LEVELS[id].ages, count: bank[id].length }))
};
const manifestText = `${JSON.stringify(manifest, null, 2)}\n`;
const total = all.length;
const room = ROOMS.find((r) => r.id === 'teasers');
const meta = `${total.toLocaleString('en-US')} teasers · 3 levels · English or Spanish`;
if (room && room.meta !== meta) err(`sections.js: the teasers room meta should read "${meta}"`);

const credits = `# Math Brain Teasers — sources

Generated by \`node tools/teaserscheck.mjs --write\`. Do not edit by hand.

Every teaser here was found in the source listed and retold in plain words
for children, in English and Spanish; none is copied word for word. Numbers
and units were sometimes made smaller or modern to suit the age.

## Rights

A math puzzle's idea is not owned, but a particular author's telling of it
can be, and so can a puzzle someone made up recently. So each teaser records
who, if anyone, owns it, and only two kinds are kept:

- **public domain**: from a book published before 1929 (Dudeney, Carroll,
  Loyd, Hoffmann, Rouse Ball) or an ancient or medieval source (Alcuin, the
  Greek Anthology, Sunzi, Fibonacci). \`origin\` names the work.
- **traditional**: a folk riddle with no known author that circulates
  widely. Each one lists, in \`alsoFound\`, two more unrelated places it
  appears, besides the source it was taken from. Plain exercises and math
  facts that no one could own ("how many days are in two weeks") are marked
  the same way, without links.

Puzzles made up by a modern author or contest (UKMT, Math Kangaroo, NRICH's
own tasks, a blogger's own puzzle) were taken out and replaced, and
\`tools/teaserscheck.mjs\` refuses them. This is a careful line, not legal
advice; a family or school with a different line to hold can filter on the
\`rights\` field.

Every numeric answer carries a \`check\` sum, and \`tools/teaserscheck.mjs\`
works it out and holds the right choice to it. That catches a slip, not a
wrong idea: a few sums only restate the answer. So every answer was also
worked out by hand when the bank was reviewed (2026-09-25), and teasers that
were ambiguous, disputed, or the same puzzle with new numbers were left out.

## Spanish

The Spanish was written alongside the English and then proofread against it
for meaning, wordplay that does not survive translation, agreement and
Mexican and US usage. It has not yet been read by a native speaker; each
level file records that review in \`esReview\` when it happens, and the
checker warns until it does.

${LEVEL_IDS.map((level) => `## ${LEVELS[level].name.en} (ages ${LEVELS[level].ages}), ${bank[level].length} teasers

| Id | Teaser | Rights | Source |
|---|---|---|---|
${bank[level].map((x) => `| ${x.id} | ${String(x.q?.en || '').replace(/\|/g, '\\|').replace(/\s+/g, ' ')} | ${x.rights || '?'} | [${String(x.sourceName || 'source').replace(/[[\]|]/g, '')}](${x.source}) |`).join('\n')}
`).join('\n')}`;

if (process.argv.includes('--write')) {
  fs.writeFileSync(MANIFEST, manifestText);
  fs.mkdirSync('docs/research/teasers', { recursive: true });
  fs.writeFileSync(CREDITS, credits);
  console.log(`wrote ${MANIFEST} and ${CREDITS}`);
} else {
  if (!fs.existsSync(MANIFEST) || fs.readFileSync(MANIFEST, 'utf8') !== manifestText) {
    err(`${MANIFEST} is out of date; run node tools/teaserscheck.mjs --write`);
  }
  if (!fs.existsSync(CREDITS) || fs.readFileSync(CREDITS, 'utf8') !== credits) {
    err(`${CREDITS} is out of date; run node tools/teaserscheck.mjs --write`);
  }
}

console.log(`${total} teasers: ${LEVEL_IDS.map((l) => `${bank[l].length} ${l}`).join(', ')}`);
if (warnings.length) {
  console.log(`\nwarnings (${warnings.length}):`);
  warnings.forEach((m) => console.log(`  ! ${m}`));
}
if (errors.length) {
  console.log(`\nERRORS (${errors.length}):`);
  errors.forEach((m) => console.log(`  x ${m}`));
  process.exit(1);
}
console.log('\nNo errors.');
